'use client';
import React from 'react';
import type { Metadata } from 'next';
import { Provider } from 'react-redux';
import { I18nextProvider } from 'react-i18next';

import { I18n } from '../configs/i18n';
import { store } from '../stores';

import GlobalStyle from '../assets/styles/globalStyles';
import PublicLayout from '@/src/layouts/publicLayout/PublicLayout';

export const metadata: Metadata = {
  title: 'AES TEAM',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body>
        <GlobalStyle />
        <Provider store={store}>
          <I18nextProvider i18n={I18n}>
            <PublicLayout>{children}</PublicLayout>
          </I18nextProvider>
        </Provider>
      </body>
    </html>
  );
}
